# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1817d82808171a22eb18f9ead773715c106def19b8b0c1f0f7968aa0469bfd6be96b66b624eaf24cbdb56c1963cccea8285a7255ae1fe445d66c73a99a71162

test:
  secret_key_base: 9e68e95ec52b798139c6e54a31c7c9e4f0cf5d69c0f5344a966288261a8822b745945d64a41483310a337bae72be8a45ee937b96f55f139d2db3e39d2701cb49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
